refactor: add typescript [ECO-960]
contentstack/contentstack-nextjs-starter-app pull request #33
Opened 2022-05-17 05:50 UTC by karantalapalli

refactor: add typescript [ECO-960]

2022-05-17 06:28 UTC, surajcontentstack requested changes
Couple of changes:
1- I think its better not to use Object as type. It will create conflict with the native Object.
Rename it to something more relevant 
2- Moving all the type definitions out into separate file is not required. Doing so is good practice for commonly used types. But for components prop types, it makes sense to define them in the component file itself. That way its easy to quickly check the props.

2022-05-17 06:28 UTC, surajcontentstack commented on typescript/layout.ts
> +type Object = {
I think its better not to use Object as type. It will create conflict with the native Object.
Rename it to something more relavant

2022-05-17 06:28 UTC, surajcontentstack commented on typescript/pages.ts
> +type Object = {
I think its better not to use Object as type. It will create conflict with the native Object.
Rename it to something more relavant

2022-05-17 09:33 UTC, abhishek305 reviewed
@karantalapalli 
make sure to not use **any** type only use it if the object type is unknown

2022-05-17 09:33 UTC, abhishek305 commented on components/footer.tsx
> +  function buildNavigation(ent: Entry, ft: any) {
footer response should not be any & can be provided as an object(refer to type created for footer)

2022-05-17 09:33 UTC, abhishek305 commented on components/header.tsx
> +  function buildNavigation(ent: Entry, hd: any) {
header response should not be any & can be provided as an object(refer to type created for header)

2022-05-17 09:33 UTC, abhishek305 commented on components/layout.tsx
> +  function buildNavigation(ent: Entry, hd: any, ft: any) {
similar to what mentioned in above comments for header/footer

2022-05-17 09:43 UTC, Amitkanswal commented on components/blog-list.tsx
>    let body = typeof bloglist.body === 'string' && bloglist.body.substr(0, 300);
make let body:string once

2022-05-17 09:43 UTC, Amitkanswal commented on components/blog-list.tsx
> +  const stringLength = (body as string).lastIndexOf(' ');
remove body as string from here

2022-05-17 09:43 UTC, Amitkanswal commented on package.json
> +  "version": "0.1.0",
version should not down grade from 1.4.0 to 0.1.0. this should be 2.0.0

2022-05-18 05:53 UTC, surajcontentstack approved these changes

2022-05-18 05:56 UTC, abhishek305 approved these changes

2022-05-18 06:07 UTC, Amitkanswal approved these changes

2022-06-02 06:18 UTC, merged